<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="defaultname"
    nsURI="http://defaultname/1.0" nsPrefix="defaultname">
  <eClassifiers xsi:type="ecore:EDataType" name="EDataType0">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="EDataType0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EEnum0"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EDataType1"/>
  <eClassifiers xsi:type="ecore:EClass" name="Main">
    <eOperations name="Main"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPlayer"/>
  <eSubpackages name="Vue">
    <eClassifiers xsi:type="ecore:EClass" name="Vue">
      <eOperations name="Vue">
        <eParameters name="modele" eType="#//Modele/Modele"/>
      </eOperations>
      <eOperations name="getVueBrowser" upperBound="2" eType="#//Vue/VueBrowser"/>
      <eOperations name="getVueCrossfinder" upperBound="2" eType="#//Vue/VueCrossfinder"/>
      <eOperations name="getVueKinect" upperBound="2" eType="#//Vue/VueKinect"/>
      <eOperations name="getVuePlayP1" upperBound="2" eType="#//Vue/VuePlay"/>
      <eOperations name="getVuePlayP2" upperBound="2" eType="#//Vue/VuePlay"/>
      <eOperations name="getModele"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Vue/Vue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="EReference1" eType="#//Vue/VueBrowser"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modele"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vueBrowser"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vueCrossfinder"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vueKinect"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vuePlayP1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vuePlayP2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialVersionUID"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VueBrowser">
      <eOperations name="VueBrowser">
        <eParameters name="vue" eType="#//Vue/Vue"/>
      </eOperations>
      <eOperations name="getVueBrowserTree"/>
      <eOperations name="getVueBrowserTable"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vueBrowserTree"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vueBrowserTable"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vue"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VuePlay">
      <eOperations name="VuePlay">
        <eParameters name="couleur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="vue" eType="#//Vue/Vue"/>
        <eParameters name="modelePlay" eType="#//Modele/ModelePlay"/>
      </eOperations>
      <eOperations name="paintComponent"/>
      <eOperations name="getFormatMMSS" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="getImageBackground"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageBackground"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageButton"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="couleur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imagePitchCursor"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelePlay"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vue"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vueSpectre"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VueKinect">
      <eOperations name="VueKinect">
        <eParameters name="vue" eType="#//Vue/Vue"/>
      </eOperations>
      <eOperations name="setKinectImage">
        <eParameters name="kinectImage"/>
        <eParameters name="kinectImage"/>
        <eParameters name="kinectImage"/>
      </eOperations>
      <eOperations name="paintComponent">
        <eParameters name="Graphics"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vue"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="crossfinder"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kinectImage"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kinectImageLeft"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kinectImageRight"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pause"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="play"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VueCrossfinder">
      <eOperations name="VueCorssfinder">
        <eParameters name="vue" eType="#//Vue/Vue"/>
      </eOperations>
      <eOperations name="getImageBackground"/>
      <eOperations name="paintComponent(Graphics)"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageBackground"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageCrossfinderCursor"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageDisplayVolumeOver"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageVolumeCursor"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vue"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="EEnum0"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EDataType0"/>
    <eClassifiers xsi:type="ecore:EClass" name="ModeleFieTree">
      <eOperations name="VueFileTree"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VueCrossfinderOver">
      <eOperations name="VueCrossfinderOver"/>
      <eOperations name="paintComponent"/>
      <eOperations name="displayVolumeP1">
        <eParameters name="left" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="right" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="setVolumeP1">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="setVolumeP2">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="setCrossfinder">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="displayVolumeP2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VueBrowserTree">
      <eOperations name="VueBrowserTree"/>
      <eOperations name="buildNode"/>
      <eOperations name="getChild"/>
      <eOperations name="getChildCount"/>
      <eOperations name="getLength" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getNode"/>
      <eOperations name="getScroll" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getScrollBarState"/>
      <eOperations name="isLeaf" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="paintComponent"/>
      <eOperations name="paintNode"/>
      <eOperations name="paintRoot"/>
      <eOperations name="setLength">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="setScroll">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="setScrollBarState"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageBackground"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageScrollBar"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageTree"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="root"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scroll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scrollBarState"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VueBrowserTable">
      <eOperations name="VueBrowserTable"/>
      <eOperations name="paintComponent"/>
      <eOperations name="getExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="filePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getFilePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="getLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getScroll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="paintNode">
        <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="setLength"/>
      <eOperations name="setScroll"/>
      <eOperations name="setScrollBarState">
        <eParameters name="value"/>
      </eOperations>
      <eOperations name="setTableOver"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableOver"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageBackground"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathList"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scrollBarState"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scroll"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="length"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageScrollBar"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageTable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VueSpectre">
      <eOperations name="vueSpectre">
        <eParameters name="" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="get">
        <eParameters name="current" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="total" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="player" eType="#//IPlayer"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="couleur" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Controle">
    <eClassifiers xsi:type="ecore:EClass" name="Controle">
      <eOperations name="Controle">
        <eParameters name="vue" eType="#//Vue/Vue"/>
        <eParameters name="modele" eType="#//Modele/Modele"/>
      </eOperations>
      <eOperations name="getVue" upperBound="2" eType="#//Vue/Vue"/>
      <eOperations name="getModele" upperBound="2" eType="#//Modele/Modele"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vue"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modele"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Controle -> Modele" eType="#//Modele/Modele"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ControleCrossfinder">
      <eOperations name="ControleCrossfinder">
        <eParameters name="controle" eType="#//Controle/Controle"/>
      </eOperations>
      <eOperations name="mouseClicked"/>
      <eOperations name="mousePressed"/>
      <eOperations name="mouseReleased"/>
      <eOperations name="mouseEntered"/>
      <eOperations name="mouseExited"/>
      <eOperations name="mouseMoved"/>
      <eOperations name="mouseDragged"/>
      <eOperations name="mouseWheelMoved"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modeleCrossfinder"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vueCrossfinder"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockOver" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockSelected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Modele/IModeleCrossfiner"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ControlePlay">
      <eOperations name="ControlePlay">
        <eParameters name="vuePlay" eType="#//Vue/VuePlay"/>
        <eParameters name="modelePlay" eType="#//Modele/ModelePlay"/>
      </eOperations>
      <eOperations name="mouseClicked"/>
      <eOperations name="mousePressed"/>
      <eOperations name="mouseReleased"/>
      <eOperations name="mouseEntered"/>
      <eOperations name="mouseExited"/>
      <eOperations name="mouseMoved"/>
      <eOperations name="mouseDragged"/>
      <eOperations name="mouseWheelMoved"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vuePlay"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelePlay"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockOver" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockSelected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Modele/IModelePlay"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ControleBrowserTree">
      <eOperations name="ControleBrowserTree">
        <eParameters name="controle" eType="#//Controle/Controle"/>
      </eOperations>
      <eOperations name="mouseClicked"/>
      <eOperations name="mousePressed"/>
      <eOperations name="mouseReleased"/>
      <eOperations name="mouseEntered"/>
      <eOperations name="mouseExited"/>
      <eOperations name="mouseMoved"/>
      <eOperations name="mouseDragged"/>
      <eOperations name="mouseWheelMoved"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockOver" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockSelected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vueBrowserTree"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Modele/IModeleCrossfiner"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vueBrowserTable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ControleBrowserTable">
      <eOperations name="ControleBrowserTable"/>
      <eOperations name="mouseWhellMoved"/>
      <eOperations name="mouseClicked"/>
      <eOperations name="mouseReleased"/>
      <eOperations name="mousePressed"/>
      <eOperations name="mouseMoved"/>
      <eOperations name="mouseDragged"/>
      <eOperations name="mouseExited"/>
      <eOperations name="mouseEntered"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vueBrowserTable"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockOver" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockSelected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modele"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Modele">
    <eClassifiers xsi:type="ecore:EClass" name="Modele">
      <eOperations name="Modele" lowerBound="1" upperBound="2"/>
      <eOperations name="getVue" upperBound="2" eType="#//Vue/Vue"/>
      <eOperations name="getModeleBrowser" upperBound="2" eType="#//Modele/ModeleBrowser"/>
      <eOperations name="getModeleCrossfinder" upperBound="2" eType="#//Modele/ModeleCrossfinder"/>
      <eOperations name="getModelePlayP1" upperBound="2" eType="#//Modele/ModelePlay"/>
      <eOperations name="getModelePlayP2" upperBound="2" eType="#//Modele/ModelePlay"/>
      <eOperations name="getModeleKinect" upperBound="2" eType="#//Modele/ModeleKinect"/>
      <eOperations name="setVue">
        <eParameters name="vue" eType="#//Vue/Vue"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modeleBrowser"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modeleCrossfinder"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelePlayP1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelePlayP2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modeleKinect"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Modele -> Vue" eType="#//Vue/Vue"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModeleBrowser">
      <eOperations name="ModeleBrowser">
        <eParameters name="modele" eType="#//Modele/Modele"/>
      </eOperations>
      <eOperations name="getExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="filePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modele"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelePlay">
      <eOperations name="setPlay"/>
      <eOperations name="setFilePath">
        <eParameters name="filePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="setPause"/>
      <eOperations name="ModelePlay">
        <eParameters name="modele" eType="#//Modele/Modele"/>
      </eOperations>
      <eOperations name="setPitch">
        <eParameters name="pitch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="setCurrent">
        <eParameters name="current" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="getPitch" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getTotal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="setVuePlay">
        <eParameters name="vuePlay" eType="#//Vue/VuePlay"/>
      </eOperations>
      <eOperations name="getTitle"/>
      <eOperations name="getArtist"/>
      <eOperations name="getBpm"/>
      <eOperations name="getCurrent"/>
      <eOperations name="getPlay"/>
      <eOperations name="getPause"/>
      <eOperations name="setPlay">
        <eParameters name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="setPause">
        <eParameters name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pitch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="artist" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bpm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Vue/VuePlay"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="current" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modele"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="total" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vuePlay"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="play" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pause" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Audio/IPlayer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModeleCrossfinder">
      <eOperations name="setCrossfinder">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="ModeleCrossfinder">
        <eParameters name="modele" eType="#//Modele/Modele"/>
      </eOperations>
      <eOperations name="setVolumeP1">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="setVolumeP2">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="getCrossfinder" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getVolumeP1" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getVolumeP2" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getDisplayVolumeP1"/>
      <eOperations name="getDisplayVolumeP2"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="crossfinder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="volumeP1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="volumrP2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modele"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayVolumeP1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayVolumeP2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModeleKinect">
      <eOperations name="ModeleKinect">
        <eParameters name="modele" eType="#//Modele/Modele"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modele"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModeleFileTree">
      <eOperations name="ModeleFileTree"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModeleFile">
      <eOperations name="ModeleFile"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModeleBrowserTree">
      <eOperations name="ModeleBrowserTree"/>
      <eOperations name="addChild"/>
      <eOperations name="setExpanded"/>
      <eOperations name="getPath" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getName" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getChild"/>
      <eOperations name="getChildCount" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getNode"/>
      <eOperations name="isExpanded" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isLeaf" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="removeChildren"/>
      <eOperations name="getLeafCount" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="children"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="childCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parent"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="childIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expanded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="leaf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IModeleCrossfiner">
      <eOperations name="setCrossfinder">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="setVolumeP1">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="setVolumeP2">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="getCrossfinder" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getVolumeP1" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getVolumeP2" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Modele/ModeleCrossfinder"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Modele/ModeleCrossfinder"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IModelePlay">
      <eOperations name="setPlay"/>
      <eOperations name="setPause"/>
      <eOperations name="setPitch">
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="setCurrent"/>
      <eOperations name="getPitch" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getCurrent" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Modele/ModelePlay"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Controle/ControlePlay"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Modele/ModelePlay"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Kinect">
    <eClassifiers xsi:type="ecore:EClass" name="Kinect">
      <eOperations name="Kinect"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Modele/IModeleCrossfiner"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Modele/IModelePlay"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Modele/IModeleCrossfiner"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MainPosition">
      <eOperations name="MainPosition"/>
      <eOperations name="add">
        <eParameters name="long" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
        <eParameters name="center"/>
        <eParameters name="depth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eOperations>
      <eOperations name="add">
        <eParameters name="depth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eOperations>
      <eOperations name="get">
        <eParameters name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="positions"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Audio">
    <eClassifiers xsi:type="ecore:EClass" name="Player">
      <eOperations name="setPlay"/>
      <eOperations name="setPause"/>
      <eOperations name="setVolume">
        <eParameters name="gain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      </eOperations>
      <eOperations name="Audio">
        <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      </eOperations>
      <eOperations name="setVitesse">
        <eParameters name="vitesse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      </eOperations>
      <eOperations name="setPosition">
        <eParameters name="MicroSecond" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      </eOperations>
      <eOperations name="getPosition" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eOperations name="run"/>
      <eOperations name="init"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vitesse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="file"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="runner"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioInputStream"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioFormat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gainControl"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Audio/Player"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IPlayer">
      <eOperations name="setPlay"/>
      <eOperations name="setPause"/>
      <eOperations name="setVolume">
        <eParameters name="volume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      </eOperations>
      <eOperations name="setVitesse">
        <eParameters name="volume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      </eOperations>
      <eOperations name="setPosition">
        <eParameters name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      </eOperations>
      <eOperations name="getPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Audio/Player"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Modele/ModelePlay"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="EPackage0"/>
</ecore:EPackage>
